# Generated by Django 5.1.7 on 2025-03-11 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_companies', '0002_devices_requires_credentials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devices',
            name='requires_credentials',
        ),
        migrations.AddField(
            model_name='devices',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='كلمة المرور'),
        ),
        migrations.AddField(
            model_name='devices',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='اسم المستخدم'),
        ),
    ]
