# Generated by Django 5.1.7 on 2025-03-12 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_companies', '0005_devices_requires_credentials_alter_devices_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devices',
            name='requires_credentials',
        ),
        migrations.AlterField(
            model_name='devices',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='كلمة المرور'),
        ),
        migrations.AlterField(
            model_name='devices',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم المستخدم'),
        ),
    ]
