# Generated by Django 5.1.4 on 2025-03-12 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_companies', '0006_remove_devices_requires_credentials_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='baud_rate',
            field=models.CharField(choices=[('9600', '9600'), ('19200', '19200'), ('38400', '38400'), ('57600', '57600'), ('115200', '115200')], default='9600', max_length=50, verbose_name='معدل الباود'),
        ),
        migrations.AlterField(
            model_name='devices',
            name='initialization_data_size',
            field=models.PositiveIntegerField(choices=[('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], default=8, verbose_name='حجم بيانات التهيئة'),
        ),
        migrations.AlterField(
            model_name='devices',
            name='number_of_initialization_bits',
            field=models.PositiveIntegerField(choices=[('1', '1'), ('2', '2')], default=1, verbose_name='عدد بتات التهيئة'),
        ),
    ]
