# Generated by Django 5.1.4 on 2025-03-13 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_companies', '0007_alter_devices_baud_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='initialization_data_size',
            field=models.PositiveIntegerField(choices=[(5, '5'), (6, '6'), (7, '7'), (8, '8')], default=8, verbose_name='حجم بيانات التهيئة'),
        ),
        migrations.AlterField(
            model_name='devices',
            name='number_of_initialization_bits',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2')], default=1, verbose_name='عدد بتات التهيئة'),
        ),
    ]
