# Generated by Django 5.1.4 on 2025-03-12 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferredWeightCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='اسم الشركة')),
                ('plate_number', models.CharField(max_length=50, verbose_name='رقم اللوحة')),
                ('empty_weight', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='الوزن الفارغ')),
                ('loaded_weight', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='الوزن المحمل')),
                ('net_weight', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='الوزن الصافي')),
                ('driver_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم السائق')),
                ('entry_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الدخول')),
                ('exit_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الخروج')),
                ('quantity', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='الكمية')),
                ('material', models.CharField(blank=True, max_length=255, null=True, verbose_name='المادة')),
                ('status', models.CharField(max_length=50, verbose_name='حالة البطاقة')),
            ],
            options={
                'verbose_name': 'بطاقة وزن منقولة',
                'verbose_name_plural': 'بطاقات وزن منقولة',
            },
        ),
    ]
