# Generated by Django 5.1.4 on 2025-03-12 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies_manager', '0002_transferredweightcard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transferredweightcard',
            old_name='company_name',
            new_name='name',
        ),
    ]
