# Generated by Django 5.1.4 on 2025-03-12 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies_manager', '0003_rename_company_name_transferredweightcard_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='company_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='transferredweightcard',
            old_name='name',
            new_name='company_name',
        ),
    ]
