# Generated by Django 5.1.4 on 2025-03-13 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies_manager', '0004_rename_company_name_company_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transferredweightcard',
            old_name='material',
            new_name='name_material',
        ),
    ]
