# Generated by Django 5.1.4 on 2025-03-13 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies_manager', '0006_rename_name_material_transferredweightcard_material'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='name',
            new_name='company_name',
        ),
    ]
